export const sectorSpartak = () => {
    return {
        'part1': [],
        'part2': [],
        'part3': [],
        'part4': [],
        'part5': [],
        'part6': [],
        'part7': [],
        'part8': [],
        'part9': [],
        'part10': [],
        'part11': [],
        'part12': [],
        'part13': [],
        'part14': [],
        'part15': [],
        'part16': [],
        'part17': [],
        'part18': [],
        'part19': [],
        'part20': [],
        'part21': [],
        'part22': [],
        'part23': [],
        'part24': [],
        'part25': [],
        'part26': [],
        'part27': [],
        'part28': [],
        'VIP': [],
        'without': true,
    }
};