export const part11 =
    [
    [
        {name: 'ряд 5:22 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
        {name: 'ряд 5:21 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
        {name: 'ряд 5:20 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
        {name: 'ряд 5:19 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
        {name: 'ряд 5:18 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
        {name: 'ряд 5:17 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
        {name: 'ряд 5:16 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
        {name: 'ряд 5:15 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
        {name: 'ряд 5:14 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
        {name: 'ряд 5:13 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
        {name: 'ряд 5:12 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
        {name: 'ряд 5:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
        {name: 'ряд 5:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
        {name: 'ряд 5:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
        {name: 'ряд 5:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
        {name: 'ряд 5:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
        {name: 'ряд 5:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
        {name: 'ряд 5:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
        {name: 'ряд 5:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
        {name: 'ряд 5:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
        {name: 'ряд 5:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
        {name: 'ряд 5:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
        {name: 'ряд 5:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
        {name: 'ряд 5:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
        {name: 'ряд 5:11 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
        {name: 'ряд 5:10 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
        {name: 'ряд 5:9 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
        {name: 'ряд 5:8 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
        {name: 'ряд 5:7 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
        {name: 'ряд 5:6 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
        {name: 'ряд 5:5 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
        {name: 'ряд 5:4 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
        {name: 'ряд 5:3 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
        {name: 'ряд 5:2 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
        {name: 'ряд 5:1 место', status: 'block', type: 'seat', price: '0', color: 'gray'}
    ],[
        {name: 'ряд 4:22 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 4:21 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 4:20 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 4:19 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 4:18 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 4:17 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 4:16 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 4:15 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 4:14 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 4:13 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 4:12 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 4:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
    {name: 'ряд 4:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
    {name: 'ряд 4:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
    {name: 'ряд 4:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
    {name: 'ряд 4:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
    {name: 'ряд 4:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
    {name: 'ряд 4:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
    {name: 'ряд 4:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
    {name: 'ряд 4:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
    {name: 'ряд 4:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
    {name: 'ряд 4:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
    {name: 'ряд 4:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
    {name: 'ряд 4:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
    {name: 'ряд 4:11 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 4:10 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 4:9 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 4:8 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 4:7 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 4:6 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 4:5 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 4:4 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 4:3 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 4:2 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 4:1 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
],[
    {name: 'ряд 3:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
    {name: 'ряд 3:30 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 3:29 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 3:28 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 3:27 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 3:26 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 3:25 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 3:24 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 3:23 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 3:22 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 3:21 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 3:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
    {name: 'ряд 3:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
    {name: 'ряд 3:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
    {name: 'ряд 3:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
    {name: 'ряд 3:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
    {name: 'ряд 3:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
    {name: 'ряд 3:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
    {name: 'ряд 3:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
    {name: 'ряд 3:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
    {name: 'ряд 3:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
    {name: 'ряд 3:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
    {name: 'ряд 3:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
    {name: 'ряд 3:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
    {name: 'ряд 3:20 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 3:19 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 3:18 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 3:17 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 3:16 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 3:15 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 3:14 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 3:13 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 3:12 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 3:11 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 3:10 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
],[
    {name: 'ряд 2:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
    {name: 'ряд 2:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
    {name: 'ряд 2:36 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 2:35 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 2:34 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 2:32 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 2:37 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 2:31 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 2:30 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 2:29 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 2:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
    {name: 'ряд 2:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
    {name: 'ряд 2:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
    {name: 'ряд 2:28 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 2:27 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 2:26 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 2:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
    {name: 'ряд 2:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
    {name: 'ряд 2:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
    {name: 'ряд 2:25 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 2:24 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 2:23 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 2:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
    {name: 'ряд 2:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
    {name: 'ряд 2:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
    {name: 'ряд 2:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
    {name: 'ряд 2:22 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 2:21 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 2:20 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 2:19 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 2:18 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 2:17 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 2:16 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 2:15 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 2:14 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
],[
       {name: 'ряд 1:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
    {name: 'ряд 1:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
    {name: 'ряд 1:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
    {name: 'ряд 1:34 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 1:33 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 1:32 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 1:31 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 1:30 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 1:29 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 1:28 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 1:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
    {name: 'ряд 1:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
    {name: 'ряд 1:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
    {name: 'ряд 1:27 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 1:26 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 1:25 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 1:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
    {name: 'ряд 1:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
    {name: 'ряд 1:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
    {name: 'ряд 1:24 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 1:23 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 1:22 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 1:21 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 1:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
    {name: 'ряд 1:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
    {name: 'ряд 1:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
    {name: 'ряд 1:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
    {name: 'ряд 1:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
    {name: 'ряд 1:20 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 1:19 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 1:18 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 1:17 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 1:16 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 1:15 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
    {name: 'ряд 1:14 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
]
]

export const part12 =
    [
        [
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд 3:31 место', status: 'free', type: 'seat', price: '0', color: 'gray'},
        ],
        [
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд 3:32 место', status: 'free', type: 'seat', price: '0', color: 'gray'},
            {name: 'ряд 2:37 место', status: 'free', type: 'seat', price: '0', color: 'gray'},
        ],
        [
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд 3:33 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
            {name: 'ряд 2:38 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
        ],
        [
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд 3:34 место', status: 'free', type: 'seat', price: '0', color: 'gray'},
            {name: 'ряд 2:39 место', status: 'free', type: 'seat', price: '0', color: 'gray'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
        ],
        [
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд 3:35 место', status: 'free', type: 'seat', price: '0', color: 'gray'},
            {name: 'ряд 2:40 место', status: 'free', type: 'seat', price: '0', color: 'gray'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
        ],
        [
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд 3:36 место', status: 'free', type: 'seat', price: '0', color: 'gray'},
            {name: 'ряд 2:41 место', status: 'free', type: 'seat', price: '0', color: 'gray'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
        ],
        [
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд 3:37 место', status: 'free', type: 'seat', price: '0', color: 'gray'},
            {name: 'ряд 2:42 место', status: 'free', type: 'seat', price: '0', color: 'gray'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
        ],
        [
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд 3:38 место', status: 'free', type: 'seat', price: '0', color: 'gray'},
            {name: 'ряд 2:43 место', status: 'free', type: 'seat', price: '0', color: 'gray'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
        ],
        [
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд 3:39 место', status: 'free', type: 'seat', price: '0', color: 'gray'},
            {name: 'ряд 2:44 место', status: 'free', type: 'seat', price: '0', color: 'gray'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
        ],
        [
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд 3:40 место', status: 'free', type: 'seat', price: '0', color: 'gray'},
            {name: 'ряд 2:45 место', status: 'free', type: 'seat', price: '0', color: 'gray'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
        ],
        [
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд 3:41 место', status: 'free', type: 'seat', price: '0', color: 'gray'},
            {name: 'ряд 2:46 место', status: 'free', type: 'seat', price: '0', color: 'gray'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
        ],
        [
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд 3:42 место', status: 'free', type: 'seat', price: '0', color: 'gray'},
            {name: 'ряд 2:47 место', status: 'free', type: 'seat', price: '0', color: 'gray'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
        ],
        [
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд 3:43 место', status: 'free', type: 'seat', price: '0', color: 'gray'},
            {name: 'ряд 2:48 место', status: 'free', type: 'seat', price: '0', color: 'gray'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
        ],
        [
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд 3:44 место', status: 'free', type: 'seat', price: '0', color: 'gray'},
            {name: 'ряд 2:49 место', status: 'free', type: 'seat', price: '0', color: 'gray'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
        ],
        [
            {name: 'ряд 3:50 место', status: 'free', type: 'seat', price: '0', color: 'gray'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд L:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
        ]
    ]


export const part13 =
    [
        [
            {name: 'ряд 3:9 место', status: 'free', type: 'seat', price: '0', color: 'gray'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
        ],
        [
            {name: 'ряд 2:13 место', status: 'free', type: 'seat', price: '0', color: 'gray'},
            {name: 'ряд 3:8 место', status: 'free', type: 'seat', price: '0', color: 'gray'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
        ],
        [
            {name: 'ряд 1:13 место', status: 'free', type: 'seat', price: '0', color: 'gray'},
            {name: 'ряд 2:12 место', status: 'free', type: 'seat', price: '0', color: 'gray'},
            {name: 'ряд 3:7 место', status: 'free', type: 'seat', price: '0', color: 'gray'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
        ],
        [
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд 1:12 место', status: 'free', type: 'seat', price: '0', color: 'gray'},
            {name: 'ряд 2:11 место', status: 'free', type: 'seat', price: '0', color: 'gray'},
            {name: 'ряд 3:6 место', status: 'free', type: 'seat', price: '0', color: 'gray'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
        ],
        [
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд 1:11 место', status: 'free', type: 'seat', price: '0', color: 'gray'},
            {name: 'ряд 2:10 место', status: 'free', type: 'seat', price: '0', color: 'gray'},
            {name: 'ряд 3:5 место', status: 'free', type: 'seat', price: '0', color: 'gray'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
        ],
        [
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд 1:10 место', status: 'free', type: 'seat', price: '0', color: 'gray'},
            {name: 'ряд 2:9 место', status: 'free', type: 'seat', price: '0', color: 'gray'},
            {name: 'ряд 3:4 место', status: 'free', type: 'seat', price: '0', color: 'gray'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
        ],
        [
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд 1:9 место', status: 'free', type: 'seat', price: '0', color: 'gray'},
            {name: 'ряд 2:8 место', status: 'free', type: 'seat', price: '0', color: 'gray'},
            {name: 'ряд 3:3 место', status: 'free', type: 'seat', price: '0', color: 'gray'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
        ],
        [
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд 1:8 место', status: 'free', type: 'seat', price: '0', color: 'gray'},
            {name: 'ряд 2:7 место', status: 'free', type: 'seat', price: '0', color: 'gray'},
            {name: 'ряд 3:2 место', status: 'free', type: 'seat', price: '0', color: 'gray'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
        ],
        [
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд 1:7 место', status: 'free', type: 'seat', price: '0', color: 'gray'},
            {name: 'ряд 2:6 место', status: 'free', type: 'seat', price: '0', color: 'gray'},
            {name: 'ряд 3:1 место', status: 'free', type: 'seat', price: '0', color: 'gray'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
        ],
        [
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд 1:6 место', status: 'free', type: 'seat', price: '0', color: 'gray'},
            {name: 'ряд 2:5 место', status: 'free', type: 'seat', price: '0', color: 'gray'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
        ],
        [
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд 1:5 место', status: 'free', type: 'seat', price: '0', color: 'gray'},
            {name: 'ряд 2:4 место', status: 'free', type: 'seat', price: '0', color: 'gray'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
        ],
        [
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд 1:4 место', status: 'free', type: 'seat', price: '0', color: 'gray'},
            {name: 'ряд 2:3 место', status: 'free', type: 'seat', price: '0', color: 'gray'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
        ],
        [
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд 1:3 место', status: 'free', type: 'seat', price: '0', color: 'gray'},
            {name: 'ряд 2:2 место', status: 'free', type: 'seat', price: '0', color: 'gray'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
        ],
        [
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд 1:2 место', status: 'free', type: 'seat', price: '0', color: 'gray'},
            {name: 'ряд 2:1 место', status: 'free', type: 'seat', price: '0', color: 'gray'},
        ],
        [
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд R:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            {name: 'ряд 1:1 место', status: 'free', type: 'seat', price: '0', color: 'gray'},
        ],
    ]