export const sectorPhilharmonicSmall     = () => {
    return {
        'part1': [
            [
                {name: 'ряд 9:42 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 9:41 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 9:40 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 9:39 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 9:38 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 9:37 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 9:36 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 9:35 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 9:34 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 9:33 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 9:32 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 9:31 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 9:30 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 9:29 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
            ],[
                {name: 'ряд 8:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
                {name: 'ряд 8:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
                {name: 'ряд 8:34 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 8:33 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 8:32 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 8:31 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 8:30 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 8:29 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 8:28 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 8:27 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 8:26 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 8:25 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 8:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
                {name: 'ряд 8:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            ],[
                {name: 'ряд 7:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
                {name: 'ряд 7:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
                {name: 'ряд 7:34 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 7:33 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 7:32 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 7:31 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 7:30 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 7:29 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 7:28 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 7:27 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 7:26 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 7:25 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 7:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
                {name: 'ряд 7:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            ],[
                {name: 'ряд 6:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
                {name: 'ряд 6:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
                {name: 'ряд 6:34 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 6:33 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 6:32 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 6:31 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 6:30 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 6:29 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 6:28 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 6:27 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 6:26 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 6:25 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 6:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
                {name: 'ряд 6:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            ],[
                {name: 'ряд 5:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
                {name: 'ряд 5:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
                {name: 'ряд 5:34 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 5:33 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 5:32 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 5:31 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 5:30 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 5:29 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 5:28 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 5:27 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 5:26 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 5:25 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 5:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
                {name: 'ряд 5:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            ],[
                {name: 'ряд 4:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
                {name: 'ряд 4:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
                {name: 'ряд 4:34 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 4:33 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 4:32 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 4:31 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 4:30 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 4:29 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 4:28 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 4:27 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 4:26 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 4:25 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 4:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
                {name: 'ряд 4:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            ],[
                {name: 'ряд 3:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
                {name: 'ряд 3:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
                {name: 'ряд 3:34 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 3:33 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 3:32 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 3:31 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 3:30 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 3:29 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 3:28 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 3:27 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 3:26 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 3:25 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 3:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
                {name: 'ряд 3:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            ],[
                {name: 'ряд 2:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
                {name: 'ряд 2:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
                {name: 'ряд 2:34 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 2:33 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 2:32 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 2:31 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 2:30 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 2:29 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 2:28 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 2:27 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 2:26 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 2:25 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 2:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
                {name: 'ряд 2:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            ],[
                {name: 'ряд 1:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
                {name: 'ряд 1:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
                {name: 'ряд 1:34 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 1:33 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 1:32 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 1:31 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 1:30 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 1:29 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 1:28 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 1:27 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 1:26 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 1:25 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 1:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
                {name: 'ряд 1:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            ]
        ],
        'part2': [
            [
                {name: 'ряд 9:28 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 9:27 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 9:26 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 9:25 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 9:24 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 9:23 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 9:22 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 9:21 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 9:20 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 9:19 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 9:18 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 9:17 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 9:16 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 9:15 место', status: 'block', type: 'seat', price: '0', color: 'gray'}
            ],[
                {name: 'ряд 8:24 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 8:23 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 8:22 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 8:21 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 8:20 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 8:19 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 8:18 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 8:17 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 8:16 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 8:15 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 8:14 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 8:13 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 8:12 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 8:11 место', status: 'block', type: 'seat', price: '0', color: 'gray'}
            ],[
                {name: 'ряд 7:24 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 7:23 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 7:22 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 7:21 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 7:20 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 7:19 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 7:18 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 7:17 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 7:16 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 7:15 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 7:14 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 7:13 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 7:12 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 7:11 место', status: 'block', type: 'seat', price: '0', color: 'gray'}
            ],[
                {name: 'ряд 6:24 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 6:23 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 6:22 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 6:21 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 6:20 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 6:19 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 6:18 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 6:17 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 6:16 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 6:15 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 6:14 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 6:13 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 6:12 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 6:11 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
            ],[
                {name: 'ряд 5:24 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 5:23 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 5:22 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 5:21 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 5:20 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 5:19 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 5:18 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 5:17 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 5:16 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 5:15 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 5:14 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 5:13 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 5:12 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 5:11 место', status: 'block', type: 'seat', price: '0', color: 'gray'}
            ],[
                {name: 'ряд 4:24 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 4:23 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 4:22 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 4:21 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 4:20 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 4:19 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 4:18 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 4:17 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 4:16 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 4:15 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 4:14 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 4:13 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 4:12 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 4:11 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
            ],[
                {name: 'ряд 3:24 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 3:23 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 3:22 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 3:21 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 3:20 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 3:19 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 3:18 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 3:17 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 3:16 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 3:15 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 3:14 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 3:13 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 3:12 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 3:11 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
            ],[
                {name: 'ряд 2:24 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 2:23 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 2:22 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 2:21 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 2:20 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 2:19 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 2:18 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 2:17 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 2:16 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 2:15 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 2:14 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 2:13 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 2:12 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 2:11 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
            ],[
                {name: 'ряд 1:24 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 1:23 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 1:22 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 1:21 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 1:20 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 1:19 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 1:18 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 1:17 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 1:16 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 1:15 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 1:14 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 1:13 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 1:12 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 1:11 место', status: 'block', type: 'seat', price: '0', color: 'gray'}
            ]
        ],
        'part3': [
            [
                {name: 'ряд 9:14 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 9:13 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 9:12 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 9:11 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 9:10 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 9:9 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 9:8 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 9:7 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 9:6 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 9:5 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 9:4 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 9:3 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 9:2 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 9:1 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
            ],[
                {name: 'ряд 8:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
                {name: 'ряд 8:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
                {name: 'ряд 8:10 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 8:9 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 8:8 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 8:7 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 8:6 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 8:5 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 8:4 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 8:3 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 8:2 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 8:1 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 8:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
                {name: 'ряд 8:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            ],[
                {name: 'ряд 7:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
                {name: 'ряд 7:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
                {name: 'ряд 7:10 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 7:9 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 7:8 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 7:7 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 7:6 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 7:5 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 7:4 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 7:3 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 7:2 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 7:1 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 7:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
                {name: 'ряд 7:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            ],[
                {name: 'ряд 6:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
                {name: 'ряд 6:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
                {name: 'ряд 6:10 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 6:9 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 6:8 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 6:7 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 6:6 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 6:5 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 6:4 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 6:3 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 6:2 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 6:1 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 6:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
                {name: 'ряд 6:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            ],[
                {name: 'ряд 5:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
                {name: 'ряд 5:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
                {name: 'ряд 5:10 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 5:9 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 5:8 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 5:7 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 5:6 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 5:5 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 5:4 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 5:3 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 5:2 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 5:1 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 5:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
                {name: 'ряд 5:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            ],[
                {name: 'ряд 4:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
                {name: 'ряд 4:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
                {name: 'ряд 4:10 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 4:9 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 4:8 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 4:7 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 4:6 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 4:5 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 4:4 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 4:3 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 4:2 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 4:1 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 4:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
                {name: 'ряд 4:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            ],[
                {name: 'ряд 3:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
                {name: 'ряд 3:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
                {name: 'ряд 3:10 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 3:9 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 3:8 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 3:7 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 3:6 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 3:5 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 3:4 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 3:3 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 3:2 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 3:1 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 3:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
                {name: 'ряд 3:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            ],[
                {name: 'ряд 2:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
                {name: 'ряд 2:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
                {name: 'ряд 2:10 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 2:9 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 2:8 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 2:7 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 2:6 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 2:5 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 2:4 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 2:3 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 2:2 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 2:1 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 2:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
                {name: 'ряд 2:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            ],[
                {name: 'ряд 1:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
                {name: 'ряд 1:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
                {name: 'ряд 1:10 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 1:9 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 1:8 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 1:7 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 1:6 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 1:5 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 1:4 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 1:3 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 1:2 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 1:1 место', status: 'block', type: 'seat', price: '0', color: 'gray'},
                {name: 'ряд 1:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
                {name: 'ряд 1:* место', status: 'block', type: 'empty', price: '0', color: 'transparent'},
            ]
        ]
    }
}


